name: Build and deploy dotnet core app to Azure Function App - reportfunctionservice

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: functions
  DOTNET_VERSION: 8.0.x
  DOTNET_NOLOGO: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDKs
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            ${{ env.DOTNET_VERSION }}
            6.0.x

      - name: Publish (Release)
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        run: dotnet publish -c Release -o ./publish

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: reportfunctionservice
          slot-name: Production
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/publish'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_30A0DB7E716245E1B297C7BD89E79CB1 }}
